SChernykh/p2pool

- README.md
Successfully built on Arch Linux. x86_64 AMD.
This PR is to tell new users there is a package for Arch Linux now that I'm maintaining over there. Any build issues I'm now actively maintaining for this package. I'll try and include a systemd service over there too so users can run p2pool at startup along with monerod/xmrig. Of course they will need to set that up themselves. I'm only handling p2pool here.
> Add doc section for Arch Linux AUR package

- README.md
- flake.lock
- flake.nix
This adds build instructions for [NixOS](https://nixos.org) and the flake files to go along with it. 
I found that I can omit the `libpgm-dev` and `libnorm-dev` dependency. I tried this because I didn't found those in nixpkgs. Somehow it builds and works regardless.
> Add build for Nix/NixOS

- README.md
Start cleaning up testing verbiage before blog post on Official Monero site goes live.
https://github.com/monero-project/monero-site/pull/1835/
I feel like the 'How to mine on P2Pool' section should be moved above the compile instructions since the instructions are less relevant now that binaries are released, but I held off doing it without guidance.
> remove testing verbiage

- README.md
Fix batch as requested by XvB
Run as Administrator in windows uses a different path, so '.' directory doesn't work in batch script. Using `%~dp0` which expands to the drive and path of the original batch file (NOTE: this may not work on remote locations not mounted to a drive letter i.e. //server/share, but I doubt users will be running it from a share drive).
[User pain point example.](https://www.reddit.com/r/xmrvsbeast/comments/pvij0q/p2pool_video_guide_setup/heci7os/?context=3)
> fix run as admin and add pauses

- src/main.cpp
- src/p2pool.cpp
- src/p2pool.h
- src/p2pool_api.cpp
- src/p2pool_api.h
- src/params.cpp
- src/params.h
- src/stratum_server.cpp
- src/stratum_server.h
~~Still work in progress. Please excuse the messy code.~~
Note also the purpose of this for me was not only to implement a feature I would like, but also to learn a bit of C++ as it's not a language I have dealt with much.
The intent here is to allow users to optionally enable a json file that has the values that would printed for `StratumServer status`.
Todo:
> API for stratum server statistics.

- docker-compose/.env
- docker-compose/README.md
- docker-compose/docker-compose.yml
- docker-compose/monero/Dockerfile
Latest Monero release tag begins support of p2pool.
Allow a specific release tag, or "latest" to get the most recent automatically (default)
A few more docker commands in the README
> Monero latest release supports p2pool

- README.md
Monero.com used the 4.2.8 Cake Wallet base, so all versions of that app are compatible
> Add monero.com to list of compatible wallets

- README.md
Added a link to SethForPrivacy's guide within the Linux instructions, to potentially assist those who may need a bit more hand holding, or followed his previous guide to deploy a node.
> Add a link to SethForPrivacy's Linux guide

- flake.lock
- flake.nix
It appears the new 3.x p2pool no longer builds with NixOS:
```
<...>
<artificial>:(.text+0x76f9): undefined reference to `randomx_get_flags'
/nix/store/fhzz4yrdy17czwc9i4swhlpcp445inzb-binutils-2.40/bin/ld: <artificial>:(.text+0x7718): undefined reference to `randomx_create_vm'
/nix/store/fhzz4yrdy17czwc9i4swhlpcp445inzb-binutils-2.40/bin/ld: <artificial>:(.text+0x779c): undefined reference to `randomx_vm_set_dataset'
/nix/store/fhzz4yrdy17czwc9i4swhlpcp445inzb-binutils-2.40/bin/ld: <artificial>:(.text+0x78d5): undefined reference to `randomx_calculate_hash_next'
/nix/store/fhzz4yrdy17czwc9i4swhlpcp445inzb-binutils-2.40/bin/ld: <artificial>:(.text+0x7a14): undefined reference to `randomx_vm_set_cache'
/nix/store/fhzz4yrdy17czwc9i4swhlpcp445inzb-binutils-2.40/bin/ld: …
```
> Disable LTO on NixOS builds

- src/console_commands.cpp
- src/console_commands.h
Fixes #237 to allow stdin to be a named pipe in addition to TTY.
1) `uv_guess_handle(0)` is used to determine the stdin handle type, with alternative handling for `UV_TTY` and `UV_NAMED_PIPE`; any other type produces an error and no console is initiated.
2) For `UV_TTY`, `uv_tty_init()` is used as before. 
3) For `UV_NAMED_PIPE`, `uv_pipe_init()` and `uv_pipe_oepn()` are used to initalise/open the pipe.
4) Separate members are used to store the respective `uv_tty_t` (`m_tty`, not changed) and `uv_pipe_t` (`m_stdin_pipe`) handles; `m_stdin_handle` is used as a `uv_handle_t*` reference to whichever of these was actually used.
5) Code which would needs to use the active handle now uses `m_stdin_handle`, e.g. ` uv_read_start()` and `uv_close()`.
Testing done in Linux; not tested in Windows …
> Allow named pipe as stdin

- README.md
Sorry for the inconvenience.
I've updated everything on my side, the old repo should redirect automatically too.
> README: update gupax link

- src/stratum_server.cpp
Adding workers data into stratum api file..
`{
"hashrate_15m": 1161,
"hashrate_1h": 1161,
"hashrate_24h": 1161,
"total_hashes": 97539,
"shares_found": 0,
"shares_failed": 0,
"average_effort": 0,
"current_effort": 0.124,
"connections": 2,
"incoming_connections": 2,
"block_reward_share_percent": 0.317,
"workers": [
"192.168.1.1:44628,60,2501,518,z",
"192.168.1.2:46396,64,2501,1547,y"
]
}`
Data is structured as follow : 
`ip:port,uptime,difficulty,hashrate,name`
For archive purporse, the discussion behind this update is in initial pull request https://github.com/SChernykh/p2pool/pull/277
> Adding workers data to api 

- src/p2p_server.cpp
`main.gupax.io` points to the same nodes as `seeds.p2pool.io`
`mini.gupax.io` same as `seeds-mini.p2pool.io`
Tested on main/mini as-is and with `gupax.io` as the only source.
> Add `gupax.io` to DNS seed nodes

- docker-compose/statistics/app/p2pool_statistics.py
- docker-compose/statistics/app/templates/index.html
Now since #278 was merged, the small statistics web server could display worker stats. This PR adds a (preliminary) PoC to add it.
I limited it to 30 workers as of now, but this could be simply changed. 
Also I'm not too happy with the look and feel of the site with the nested table. If someone with more HTML/bootstrap experience wants to chime in?
> add miner stats to web server output

- docker-compose/configure
Current version check fails when the patch version of docker is less than 3, even if the major version is much more recent.
Suggested fix based on GNU sort
> fix: docker version check in docker-compose configure

- docker-compose/statistics/Dockerfile
When running with Docker Compose, `docker compose down`, fails to promptly stop the containers.
This is due to the statistics container not halting when sent SIGTERM by docker, and instead times out and is then killed by docker anyway. As the container is running Python/Flask as PID 1, this receives the SIGTERM but ignores it by default.
There are many ways to fix this, but the simplest is just to get Docker to send SIGINT to this container instead.
> Fix stop signal for stats container

- src/pow_hash.cpp
The unit prefix symbol to use here should be `Mi` for prefix `mebi-`. Because the code to calculate this number is `... >> 20`, not `... / 1000000`.
> Correct unit prefix symbol for unit `mebibyte`

- src/stratum_server.cpp
- src/stratum_server.h
This allows me easily checking *when was my latest pool share found*.
Example result:
```
$ jq . < /tmp/p2pool-api/local/stratum
{
"hashrate_15m": 11314,
"hashrate_1h": 18202,
"hashrate_24h": 16265,
"total_hashes": 191561440,
"total_stratum_shares": 848,
"last_share_found_time": 1749818417,
"shares_found": 1,
"shares_failed": 0,
"average_effort": 6.350,
"current_effort": 3.200,
"connections": 4,
"incoming_connections": 4,
"block_reward_share_percent": 0.175,
...
```
> API: add `last_share_found_time` in `local/stratum`

- Dockerfile
I tried to build the image locally, but I got timeouts on archive.ubuntu.com when executing apt update, which prevented me to build the image.
I changed the base image to the slimmed down version of debian 12, which works as well and should result in a little leaner image.
After I could build the image successfully on my local machine.
If it has to be ubuntu for some reason, it's advised to use at least ubuntu:24.04 .
> update Dockerfile base image

- docs/COMMAND_LINE.MD
- src/main.cpp
- src/params.cpp
- src/params.h
- src/stratum_server.cpp
- src/stratum_server.h
adds a command line option to enforce full share validation
this option is only needed on shared mining services, and not needed on local setups where all clients are trusted.
> full share validation via cmdline option
